# Generated by Django 5.2.7 on 2025-11-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_description_poll_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='cookie_token',
            field=models.CharField(blank=True, help_text='Browser cookie token to prevent duplicate votes', max_length=64, null=True),
        ),
    ]
