# Generated by Django 5.2.7 on 2025-11-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_vote_cookie_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft deletion timestamp. Poll will be permanently deleted 30 days after this date.', null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Poll will be automatically deleted after this date. Leave blank for 90-day default.', null=True),
        ),
    ]
